baseURL = ""
languageCode = "ko-kr"
title = "My New Hugo Site"
theme = "triplemode"

[params]
favicon = "img/favicon.ico"
description = "this is description"
disqus_shortname = "mingzzis-blog"
google_analytics = "UA-130304424-1"

str_next_post = "Next post"
str_previous_post = "Previous post"
str_next_page = "Next"
str_previous_page = "Prev"

[taxonomies]
    category = "categories"
    tag = "tags"
    subcategory = "subcategories"

[permalinks]
    write-up = "/:sections/:year/:month/:day/:filename.html"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineAnchors = ""
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    style = "dracula"
    tabWidth = 4

	[params.footer]
		enable=true
		copyright = "mingzzi"

    [[params.footer.social]]
		icon = "fa-github"
		url= "https://www.github.com/ATFutures"
		label = "GitHub"

	[[params.footer.social]]
		icon = "fa-instagram"
		url= "https://www.github.com/ATFutures"
		label = "Instagram"